// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: msgtest.proto

package msgs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 要求Proto
type MProtoQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time int64 `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"` // 傳送時間
}

func (x *MProtoQ) Reset() {
	*x = MProtoQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgtest_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MProtoQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MProtoQ) ProtoMessage() {}

func (x *MProtoQ) ProtoReflect() protoreflect.Message {
	mi := &file_msgtest_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MProtoQ.ProtoReflect.Descriptor instead.
func (*MProtoQ) Descriptor() ([]byte, []int) {
	return file_msgtest_proto_rawDescGZIP(), []int{0}
}

func (x *MProtoQ) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

// 回應Proto
type MProtoA struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From  *MProtoQ `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`               // 來源訊息
	ErrID ErrID    `protobuf:"varint,2,opt,name=errID,proto3,enum=ErrID" json:"errID,omitempty"` // 錯誤編號
	Count int64    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`            // 封包計數
}

func (x *MProtoA) Reset() {
	*x = MProtoA{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgtest_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MProtoA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MProtoA) ProtoMessage() {}

func (x *MProtoA) ProtoReflect() protoreflect.Message {
	mi := &file_msgtest_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MProtoA.ProtoReflect.Descriptor instead.
func (*MProtoA) Descriptor() ([]byte, []int) {
	return file_msgtest_proto_rawDescGZIP(), []int{1}
}

func (x *MProtoA) GetFrom() *MProtoQ {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *MProtoA) GetErrID() ErrID {
	if x != nil {
		return x.ErrID
	}
	return ErrID_Success
}

func (x *MProtoA) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_msgtest_proto protoreflect.FileDescriptor

var file_msgtest_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6d, 0x73, 0x67, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x0b, 0x6d, 0x73, 0x67, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1d, 0x0a, 0x07,
	0x4d, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x51, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x5b, 0x0a, 0x07, 0x4d,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x41, 0x12, 0x1c, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x4d, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x51, 0x52, 0x04,
	0x66, 0x72, 0x6f, 0x6d, 0x12, 0x1c, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x06, 0x2e, 0x45, 0x72, 0x72, 0x49, 0x44, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x0c, 0x5a, 0x0a, 0x2f, 0x6d, 0x73, 0x67,
	0x73, 0x3b, 0x6d, 0x73, 0x67, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msgtest_proto_rawDescOnce sync.Once
	file_msgtest_proto_rawDescData = file_msgtest_proto_rawDesc
)

func file_msgtest_proto_rawDescGZIP() []byte {
	file_msgtest_proto_rawDescOnce.Do(func() {
		file_msgtest_proto_rawDescData = protoimpl.X.CompressGZIP(file_msgtest_proto_rawDescData)
	})
	return file_msgtest_proto_rawDescData
}

var file_msgtest_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_msgtest_proto_goTypes = []interface{}{
	(*MProtoQ)(nil), // 0: MProtoQ
	(*MProtoA)(nil), // 1: MProtoA
	(ErrID)(0),      // 2: ErrID
}
var file_msgtest_proto_depIdxs = []int32{
	0, // 0: MProtoA.from:type_name -> MProtoQ
	2, // 1: MProtoA.errID:type_name -> ErrID
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_msgtest_proto_init() }
func file_msgtest_proto_init() {
	if File_msgtest_proto != nil {
		return
	}
	file_msgid_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_msgtest_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MProtoQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgtest_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MProtoA); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msgtest_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msgtest_proto_goTypes,
		DependencyIndexes: file_msgtest_proto_depIdxs,
		MessageInfos:      file_msgtest_proto_msgTypes,
	}.Build()
	File_msgtest_proto = out.File
	file_msgtest_proto_rawDesc = nil
	file_msgtest_proto_goTypes = nil
	file_msgtest_proto_depIdxs = nil
}
