// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: msgping.proto

package messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 要求密鑰
type MKeyQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MKeyQ) Reset() {
	*x = MKeyQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgping_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MKeyQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MKeyQ) ProtoMessage() {}

func (x *MKeyQ) ProtoReflect() protoreflect.Message {
	mi := &file_msgping_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MKeyQ.ProtoReflect.Descriptor instead.
func (*MKeyQ) Descriptor() ([]byte, []int) {
	return file_msgping_proto_rawDescGZIP(), []int{0}
}

// 回應密鑰
type MKeyA struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"` // 密鑰
}

func (x *MKeyA) Reset() {
	*x = MKeyA{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgping_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MKeyA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MKeyA) ProtoMessage() {}

func (x *MKeyA) ProtoReflect() protoreflect.Message {
	mi := &file_msgping_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MKeyA.ProtoReflect.Descriptor instead.
func (*MKeyA) Descriptor() ([]byte, []int) {
	return file_msgping_proto_rawDescGZIP(), []int{1}
}

func (x *MKeyA) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// 要求PingProto
type MPingProtoQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time int64 `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"` // 傳送時間
}

func (x *MPingProtoQ) Reset() {
	*x = MPingProtoQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgping_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MPingProtoQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MPingProtoQ) ProtoMessage() {}

func (x *MPingProtoQ) ProtoReflect() protoreflect.Message {
	mi := &file_msgping_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MPingProtoQ.ProtoReflect.Descriptor instead.
func (*MPingProtoQ) Descriptor() ([]byte, []int) {
	return file_msgping_proto_rawDescGZIP(), []int{2}
}

func (x *MPingProtoQ) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

// 回應PingProto
type MPingProtoA struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From  *MPingProtoQ `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`    // 來源訊息
	Count int64        `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"` // 封包計數
}

func (x *MPingProtoA) Reset() {
	*x = MPingProtoA{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgping_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MPingProtoA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MPingProtoA) ProtoMessage() {}

func (x *MPingProtoA) ProtoReflect() protoreflect.Message {
	mi := &file_msgping_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MPingProtoA.ProtoReflect.Descriptor instead.
func (*MPingProtoA) Descriptor() ([]byte, []int) {
	return file_msgping_proto_rawDescGZIP(), []int{3}
}

func (x *MPingProtoA) GetFrom() *MPingProtoQ {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *MPingProtoA) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 要求PingStack
type MPingStackQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time int64 `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"` // 傳送時間
}

func (x *MPingStackQ) Reset() {
	*x = MPingStackQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgping_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MPingStackQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MPingStackQ) ProtoMessage() {}

func (x *MPingStackQ) ProtoReflect() protoreflect.Message {
	mi := &file_msgping_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MPingStackQ.ProtoReflect.Descriptor instead.
func (*MPingStackQ) Descriptor() ([]byte, []int) {
	return file_msgping_proto_rawDescGZIP(), []int{4}
}

func (x *MPingStackQ) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

// 回應PingStack
type MPingStackA struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From  *MPingStackQ `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`    // 來源訊息
	Count int64        `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"` // 封包計數
}

func (x *MPingStackA) Reset() {
	*x = MPingStackA{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgping_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MPingStackA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MPingStackA) ProtoMessage() {}

func (x *MPingStackA) ProtoReflect() protoreflect.Message {
	mi := &file_msgping_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MPingStackA.ProtoReflect.Descriptor instead.
func (*MPingStackA) Descriptor() ([]byte, []int) {
	return file_msgping_proto_rawDescGZIP(), []int{5}
}

func (x *MPingStackA) GetFrom() *MPingStackQ {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *MPingStackA) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_msgping_proto protoreflect.FileDescriptor

var file_msgping_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6d, 0x73, 0x67, 0x70, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x07, 0x0a, 0x05, 0x4d, 0x4b, 0x65, 0x79, 0x51, 0x22, 0x19, 0x0a, 0x05, 0x4d, 0x4b, 0x65, 0x79,
	0x41, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x22, 0x21, 0x0a, 0x0b, 0x4d, 0x50, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x51, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x45, 0x0a, 0x0b, 0x4d, 0x50, 0x69, 0x6e, 0x67, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x41, 0x12, 0x20, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x4d, 0x50, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x51, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x21, 0x0a,
	0x0b, 0x4d, 0x50, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x63, 0x6b, 0x51, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65,
	0x22, 0x45, 0x0a, 0x0b, 0x4d, 0x50, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x63, 0x6b, 0x41, 0x12,
	0x20, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x4d, 0x50, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x63, 0x6b, 0x51, 0x52, 0x04, 0x66, 0x72, 0x6f,
	0x6d, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x14, 0x5a, 0x12, 0x2f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x3b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msgping_proto_rawDescOnce sync.Once
	file_msgping_proto_rawDescData = file_msgping_proto_rawDesc
)

func file_msgping_proto_rawDescGZIP() []byte {
	file_msgping_proto_rawDescOnce.Do(func() {
		file_msgping_proto_rawDescData = protoimpl.X.CompressGZIP(file_msgping_proto_rawDescData)
	})
	return file_msgping_proto_rawDescData
}

var file_msgping_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_msgping_proto_goTypes = []interface{}{
	(*MKeyQ)(nil),       // 0: MKeyQ
	(*MKeyA)(nil),       // 1: MKeyA
	(*MPingProtoQ)(nil), // 2: MPingProtoQ
	(*MPingProtoA)(nil), // 3: MPingProtoA
	(*MPingStackQ)(nil), // 4: MPingStackQ
	(*MPingStackA)(nil), // 5: MPingStackA
}
var file_msgping_proto_depIdxs = []int32{
	2, // 0: MPingProtoA.from:type_name -> MPingProtoQ
	4, // 1: MPingStackA.from:type_name -> MPingStackQ
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_msgping_proto_init() }
func file_msgping_proto_init() {
	if File_msgping_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_msgping_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MKeyQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgping_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MKeyA); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgping_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MPingProtoQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgping_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MPingProtoA); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgping_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MPingStackQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgping_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MPingStackA); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msgping_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msgping_proto_goTypes,
		DependencyIndexes: file_msgping_proto_depIdxs,
		MessageInfos:      file_msgping_proto_msgTypes,
	}.Build()
	File_msgping_proto = out.File
	file_msgping_proto_rawDesc = nil
	file_msgping_proto_goTypes = nil
	file_msgping_proto_depIdxs = nil
}
