// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: raven.proto

package msgs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Raven訊息資料, 客戶端傳送給伺服器
type RavenS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageID int32      `protobuf:"varint,1,opt,name=messageID,proto3" json:"messageID,omitempty"` // 訊息編號, 設置為int32以跟proto的列舉類型統一
	Header    *anypb.Any `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`        // 標頭資料
	Request   *anypb.Any `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`      // 要求資料
}

func (x *RavenS) Reset() {
	*x = RavenS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_raven_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RavenS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RavenS) ProtoMessage() {}

func (x *RavenS) ProtoReflect() protoreflect.Message {
	mi := &file_raven_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RavenS.ProtoReflect.Descriptor instead.
func (*RavenS) Descriptor() ([]byte, []int) {
	return file_raven_proto_rawDescGZIP(), []int{0}
}

func (x *RavenS) GetMessageID() int32 {
	if x != nil {
		return x.MessageID
	}
	return 0
}

func (x *RavenS) GetHeader() *anypb.Any {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *RavenS) GetRequest() *anypb.Any {
	if x != nil {
		return x.Request
	}
	return nil
}

// Raven訊息資料, 伺服器傳送給客戶端
type RavenC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageID int32        `protobuf:"varint,1,opt,name=messageID,proto3" json:"messageID,omitempty"` // 訊息編號, 設置為int32以跟proto的列舉類型統一
	ErrID     int32        `protobuf:"varint,2,opt,name=errID,proto3" json:"errID,omitempty"`         // 錯誤編號, 設置為int32以跟proto的列舉類型統一
	Header    *anypb.Any   `protobuf:"bytes,3,opt,name=header,proto3" json:"header,omitempty"`        // 標頭資料
	Request   *anypb.Any   `protobuf:"bytes,4,opt,name=request,proto3" json:"request,omitempty"`      // 要求資料
	Respond   []*anypb.Any `protobuf:"bytes,5,rep,name=respond,proto3" json:"respond,omitempty"`      // 回應列表
}

func (x *RavenC) Reset() {
	*x = RavenC{}
	if protoimpl.UnsafeEnabled {
		mi := &file_raven_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RavenC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RavenC) ProtoMessage() {}

func (x *RavenC) ProtoReflect() protoreflect.Message {
	mi := &file_raven_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RavenC.ProtoReflect.Descriptor instead.
func (*RavenC) Descriptor() ([]byte, []int) {
	return file_raven_proto_rawDescGZIP(), []int{1}
}

func (x *RavenC) GetMessageID() int32 {
	if x != nil {
		return x.MessageID
	}
	return 0
}

func (x *RavenC) GetErrID() int32 {
	if x != nil {
		return x.ErrID
	}
	return 0
}

func (x *RavenC) GetHeader() *anypb.Any {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *RavenC) GetRequest() *anypb.Any {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *RavenC) GetRespond() []*anypb.Any {
	if x != nil {
		return x.Respond
	}
	return nil
}

// Raven訊息測試資料
type RavenTest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"` // 測試字串
}

func (x *RavenTest) Reset() {
	*x = RavenTest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_raven_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RavenTest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RavenTest) ProtoMessage() {}

func (x *RavenTest) ProtoReflect() protoreflect.Message {
	mi := &file_raven_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RavenTest.ProtoReflect.Descriptor instead.
func (*RavenTest) Descriptor() ([]byte, []int) {
	return file_raven_proto_rawDescGZIP(), []int{2}
}

func (x *RavenTest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_raven_proto protoreflect.FileDescriptor

var file_raven_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x72, 0x61, 0x76, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61,
	0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x84, 0x01, 0x0a, 0x06, 0x52, 0x61, 0x76,
	0x65, 0x6e, 0x53, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49,
	0x44, 0x12, 0x2c, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12,
	0x2e, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0xca, 0x01, 0x0a, 0x06, 0x52, 0x61, 0x76, 0x65, 0x6e, 0x43, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x49,
	0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x65, 0x72, 0x72, 0x49, 0x44, 0x12, 0x2c,
	0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x41, 0x6e, 0x79, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x2e, 0x0a, 0x07,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x41, 0x6e, 0x79, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x07,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x41, 0x6e, 0x79, 0x52, 0x07, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x22, 0x1f, 0x0a, 0x09,
	0x52, 0x61, 0x76, 0x65, 0x6e, 0x54, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x42, 0x0c, 0x5a,
	0x0a, 0x2f, 0x6d, 0x73, 0x67, 0x73, 0x3b, 0x6d, 0x73, 0x67, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_raven_proto_rawDescOnce sync.Once
	file_raven_proto_rawDescData = file_raven_proto_rawDesc
)

func file_raven_proto_rawDescGZIP() []byte {
	file_raven_proto_rawDescOnce.Do(func() {
		file_raven_proto_rawDescData = protoimpl.X.CompressGZIP(file_raven_proto_rawDescData)
	})
	return file_raven_proto_rawDescData
}

var file_raven_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_raven_proto_goTypes = []interface{}{
	(*RavenS)(nil),    // 0: RavenS
	(*RavenC)(nil),    // 1: RavenC
	(*RavenTest)(nil), // 2: RavenTest
	(*anypb.Any)(nil), // 3: google.protobuf.Any
}
var file_raven_proto_depIdxs = []int32{
	3, // 0: RavenS.header:type_name -> google.protobuf.Any
	3, // 1: RavenS.request:type_name -> google.protobuf.Any
	3, // 2: RavenC.header:type_name -> google.protobuf.Any
	3, // 3: RavenC.request:type_name -> google.protobuf.Any
	3, // 4: RavenC.respond:type_name -> google.protobuf.Any
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_raven_proto_init() }
func file_raven_proto_init() {
	if File_raven_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_raven_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RavenS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_raven_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RavenC); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_raven_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RavenTest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_raven_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_raven_proto_goTypes,
		DependencyIndexes: file_raven_proto_depIdxs,
		MessageInfos:      file_raven_proto_msgTypes,
	}.Build()
	File_raven_proto = out.File
	file_raven_proto_rawDesc = nil
	file_raven_proto_goTypes = nil
	file_raven_proto_depIdxs = nil
}
