log-crash:
  name: client-crash.log
  path: log
  json: false
  console: true
  file: true
  level: debug
  timeLayout: "2006-01-02T15:04:05.000Z"
  timeZone: "Asia/Taipei"
  maxSize: 100
  maxTime: 0
  maxBackups: 0
  compress: false

log-system:
  name: client-system.log
  path: log
  json: false
  console: true
  file: true
  level: debug
  timeLayout: "2006-01-02T15:04:05.000Z"
  timeZone: "Asia/Taipei"
  maxSize: 100
  maxTime: 0
  maxBackups: 0
  compress: false

pool:
  capacity: 0
  expire: 100ms
  preAlloc: false
  nonblocking: false
  maxBlocking: 0

metrics:
  port: 9101

auth:
  enable: true
  ip:
  port: 9000
  timeout: 1s
  delay: 100ms
  account: test-auth-0001
  update: 10

json:
  enable: true
  ip:
  port: 9001
  key: key-@@@@
  timeout: 1s
  interval: 20ms
  count: 1000
  batch: 100
  delay: 100ms
  disconnect: true

proto:
  enable: true
  ip:
  port: 9002
  key: key-####
  timeout: 1s
  interval: 20ms
  count: 1000
  batch: 100
  delay: 100ms
  disconnect: true