log-system:
  name: client-system.log
  path: log
  json: false
  console: true
  file: true
  level: debug
  timeLayout: "2006-01-02T15:04:05.000Z"
  maxSize: 100
  maxTime: 0
  maxBackups: 0
  compress: false

log-crash:
  name: client-crash.log
  path: log
  json: false
  console: true
  file: true
  level: debug
  timeLayout: "2006-01-02T15:04:05.000Z"
  maxSize: 100
  maxTime: 0
  maxBackups: 0
  compress: false

pool:
  capacity: 0
  expire: 100ms
  preAlloc: false
  nonblocking: false
  maxBlocking: 0

metrics:
  port: 9101

auth:
  enable: false
  ip:
  port: 9000
  timeout: 2s
  delay: 50ms
  account: test-auth-0001
  update: 10

json:
  enable: false
  ip:
  port: 9001
  key: key-@@@@
  timeout: 2s
  interval: 10ms
  count: 1000
  batch: 100
  delay: 50ms
  disconnect: true

proto:
  enable: false
  ip:
  port: 9002
  key: key-####
  timeout: 2s
  interval: 10ms
  count: 1000
  batch: 100
  delay: 50ms
  disconnect: true

protoRaven:
  enable: true
  ip:
  port: 9003
  key: key-####
  timeout: 2s
  interval: 10ms
  count: 1000
  batch: 100
  delay: 50ms
  disconnect: true