// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: complexmsg.proto

package msgs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 複合訊息資料
type ComplexMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Messages []*ComplexUnit `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"` // 訊息列表
}

func (x *ComplexMsg) Reset() {
	*x = ComplexMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_complexmsg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComplexMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComplexMsg) ProtoMessage() {}

func (x *ComplexMsg) ProtoReflect() protoreflect.Message {
	mi := &file_complexmsg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComplexMsg.ProtoReflect.Descriptor instead.
func (*ComplexMsg) Descriptor() ([]byte, []int) {
	return file_complexmsg_proto_rawDescGZIP(), []int{0}
}

func (x *ComplexMsg) GetMessages() []*ComplexUnit {
	if x != nil {
		return x.Messages
	}
	return nil
}

// 複合訊息單元資料
type ComplexUnit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageID int32      `protobuf:"varint,1,opt,name=messageID,proto3" json:"messageID,omitempty"` // 訊息編號, 設置為int32以跟proto的列舉類型統一
	Message   *anypb.Any `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`      // 訊息資料
}

func (x *ComplexUnit) Reset() {
	*x = ComplexUnit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_complexmsg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComplexUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComplexUnit) ProtoMessage() {}

func (x *ComplexUnit) ProtoReflect() protoreflect.Message {
	mi := &file_complexmsg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComplexUnit.ProtoReflect.Descriptor instead.
func (*ComplexUnit) Descriptor() ([]byte, []int) {
	return file_complexmsg_proto_rawDescGZIP(), []int{1}
}

func (x *ComplexUnit) GetMessageID() int32 {
	if x != nil {
		return x.MessageID
	}
	return 0
}

func (x *ComplexUnit) GetMessage() *anypb.Any {
	if x != nil {
		return x.Message
	}
	return nil
}

// 複合訊息測試資料
type ComplexTest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value int32  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ComplexTest) Reset() {
	*x = ComplexTest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_complexmsg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComplexTest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComplexTest) ProtoMessage() {}

func (x *ComplexTest) ProtoReflect() protoreflect.Message {
	mi := &file_complexmsg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComplexTest.ProtoReflect.Descriptor instead.
func (*ComplexTest) Descriptor() ([]byte, []int) {
	return file_complexmsg_proto_rawDescGZIP(), []int{2}
}

func (x *ComplexTest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ComplexTest) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_complexmsg_proto protoreflect.FileDescriptor

var file_complexmsg_proto_rawDesc = []byte{
	0x0a, 0x10, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x78, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x36, 0x0a,
	0x0a, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x78, 0x4d, 0x73, 0x67, 0x12, 0x28, 0x0a, 0x08, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x78, 0x55, 0x6e, 0x69, 0x74, 0x52, 0x08, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x22, 0x5b, 0x0a, 0x0b, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x78,
	0x55, 0x6e, 0x69, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x49, 0x44, 0x12, 0x2e, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x37, 0x0a, 0x0b, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x78, 0x54, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x2f,
	0x6d, 0x73, 0x67, 0x73, 0x3b, 0x6d, 0x73, 0x67, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_complexmsg_proto_rawDescOnce sync.Once
	file_complexmsg_proto_rawDescData = file_complexmsg_proto_rawDesc
)

func file_complexmsg_proto_rawDescGZIP() []byte {
	file_complexmsg_proto_rawDescOnce.Do(func() {
		file_complexmsg_proto_rawDescData = protoimpl.X.CompressGZIP(file_complexmsg_proto_rawDescData)
	})
	return file_complexmsg_proto_rawDescData
}

var file_complexmsg_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_complexmsg_proto_goTypes = []interface{}{
	(*ComplexMsg)(nil),  // 0: ComplexMsg
	(*ComplexUnit)(nil), // 1: ComplexUnit
	(*ComplexTest)(nil), // 2: ComplexTest
	(*anypb.Any)(nil),   // 3: google.protobuf.Any
}
var file_complexmsg_proto_depIdxs = []int32{
	1, // 0: ComplexMsg.messages:type_name -> ComplexUnit
	3, // 1: ComplexUnit.message:type_name -> google.protobuf.Any
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_complexmsg_proto_init() }
func file_complexmsg_proto_init() {
	if File_complexmsg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_complexmsg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ComplexMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_complexmsg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ComplexUnit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_complexmsg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ComplexTest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_complexmsg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_complexmsg_proto_goTypes,
		DependencyIndexes: file_complexmsg_proto_depIdxs,
		MessageInfos:      file_complexmsg_proto_msgTypes,
	}.Build()
	File_complexmsg_proto = out.File
	file_complexmsg_proto_rawDesc = nil
	file_complexmsg_proto_goTypes = nil
	file_complexmsg_proto_depIdxs = nil
}
