// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: msgid.proto

package messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 訊息編號
type MsgID int32

const (
	MsgID_Unknown MsgID = 0 // 不明/錯誤訊息編號, 此編號不可使用
	MsgID_KeyQ    MsgID = 1 // 要求密鑰
	MsgID_KeyA    MsgID = 2 // 回應密鑰
	MsgID_JsonQ   MsgID = 3 // 要求Json
	MsgID_JsonA   MsgID = 4 // 回應Json
	MsgID_ProtoQ  MsgID = 5 // 要求Proto
	MsgID_ProtoA  MsgID = 6 // 回應Proto
	MsgID_StackQ  MsgID = 7 // 要求Stack
	MsgID_StackA  MsgID = 8 // 回應Stack
)

// Enum value maps for MsgID.
var (
	MsgID_name = map[int32]string{
		0: "Unknown",
		1: "KeyQ",
		2: "KeyA",
		3: "JsonQ",
		4: "JsonA",
		5: "ProtoQ",
		6: "ProtoA",
		7: "StackQ",
		8: "StackA",
	}
	MsgID_value = map[string]int32{
		"Unknown": 0,
		"KeyQ":    1,
		"KeyA":    2,
		"JsonQ":   3,
		"JsonA":   4,
		"ProtoQ":  5,
		"ProtoA":  6,
		"StackQ":  7,
		"StackA":  8,
	}
)

func (x MsgID) Enum() *MsgID {
	p := new(MsgID)
	*p = x
	return p
}

func (x MsgID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgID) Descriptor() protoreflect.EnumDescriptor {
	return file_msgid_proto_enumTypes[0].Descriptor()
}

func (MsgID) Type() protoreflect.EnumType {
	return &file_msgid_proto_enumTypes[0]
}

func (x MsgID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgID.Descriptor instead.
func (MsgID) EnumDescriptor() ([]byte, []int) {
	return file_msgid_proto_rawDescGZIP(), []int{0}
}

var File_msgid_proto protoreflect.FileDescriptor

var file_msgid_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6d, 0x73, 0x67, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x6e, 0x0a,
	0x05, 0x4d, 0x73, 0x67, 0x49, 0x44, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77,
	0x6e, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4b, 0x65, 0x79, 0x51, 0x10, 0x01, 0x12, 0x08, 0x0a,
	0x04, 0x4b, 0x65, 0x79, 0x41, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x4a, 0x73, 0x6f, 0x6e, 0x51,
	0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x4a, 0x73, 0x6f, 0x6e, 0x41, 0x10, 0x04, 0x12, 0x0a, 0x0a,
	0x06, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x51, 0x10, 0x05, 0x12, 0x0a, 0x0a, 0x06, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x41, 0x10, 0x06, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x63, 0x6b, 0x51, 0x10,
	0x07, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x63, 0x6b, 0x41, 0x10, 0x08, 0x42, 0x14, 0x5a,
	0x12, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x3b, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msgid_proto_rawDescOnce sync.Once
	file_msgid_proto_rawDescData = file_msgid_proto_rawDesc
)

func file_msgid_proto_rawDescGZIP() []byte {
	file_msgid_proto_rawDescOnce.Do(func() {
		file_msgid_proto_rawDescData = protoimpl.X.CompressGZIP(file_msgid_proto_rawDescData)
	})
	return file_msgid_proto_rawDescData
}

var file_msgid_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_msgid_proto_goTypes = []interface{}{
	(MsgID)(0), // 0: MsgID
}
var file_msgid_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_msgid_proto_init() }
func file_msgid_proto_init() {
	if File_msgid_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msgid_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msgid_proto_goTypes,
		DependencyIndexes: file_msgid_proto_depIdxs,
		EnumInfos:         file_msgid_proto_enumTypes,
	}.Build()
	File_msgid_proto = out.File
	file_msgid_proto_rawDesc = nil
	file_msgid_proto_goTypes = nil
	file_msgid_proto_depIdxs = nil
}
