// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: msgid.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from msgid.proto</summary>
public static partial class MsgidReflection {

  #region Descriptor
  /// <summary>File descriptor for msgid.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static MsgidReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cgttc2dpZC5wcm90byqWAQoFTXNnSUQSCwoHVW5rbm93bhAAEgkKBUpzb25R",
          "EAESCQoFSnNvbkEQAhIKCgZQcm90b1EQAxIKCgZQcm90b0EQBBIPCgtQcm90",
          "b1JhdmVuURAFEg8KC1Byb3RvUmF2ZW5BEAYSCgoGTG9naW5REAcSCgoGTG9n",
          "aW5BEAgSCwoHVXBkYXRlURAJEgsKB1VwZGF0ZUEQCip5CgVFcnJJRBILCgdT",
          "dWNjZXNzEAASEQoNSnNvblVubWFyc2hhbBABEhIKDlByb3RvVW5tYXJzaGFs",
          "EAISFwoTUHJvdG9SYXZlblVubWFyc2hhbBADEhAKDFN1Ym1pdEZhaWxlZBAE",
          "EhEKDVRva2VuTm90TWF0Y2gQBUIMWgovbXNnczttc2dzYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::MsgID), typeof(global::ErrID), }, null, null));
  }
  #endregion

}
#region Enums
/// <summary>
/// 訊息編號
/// </summary>
public enum MsgID {
  /// <summary>
  /// 不明/錯誤訊息編號, 此編號不可使用
  /// </summary>
  [pbr::OriginalName("Unknown")] Unknown = 0,
  /// <summary>
  /// 要求Json
  /// </summary>
  [pbr::OriginalName("JsonQ")] JsonQ = 1,
  /// <summary>
  /// 回應Json
  /// </summary>
  [pbr::OriginalName("JsonA")] JsonA = 2,
  /// <summary>
  /// 要求Proto
  /// </summary>
  [pbr::OriginalName("ProtoQ")] ProtoQ = 3,
  /// <summary>
  /// 回應Proto
  /// </summary>
  [pbr::OriginalName("ProtoA")] ProtoA = 4,
  /// <summary>
  /// 要求ProtoRaven
  /// </summary>
  [pbr::OriginalName("ProtoRavenQ")] ProtoRavenQ = 5,
  /// <summary>
  /// 回應ProtoRaven
  /// </summary>
  [pbr::OriginalName("ProtoRavenA")] ProtoRavenA = 6,
  /// <summary>
  /// 要求登入(使用Json處理器)
  /// </summary>
  [pbr::OriginalName("LoginQ")] LoginQ = 7,
  /// <summary>
  /// 回應登入(使用Json處理器)
  /// </summary>
  [pbr::OriginalName("LoginA")] LoginA = 8,
  /// <summary>
  /// 要求更新(使用Json處理器)
  /// </summary>
  [pbr::OriginalName("UpdateQ")] UpdateQ = 9,
  /// <summary>
  /// 回應更新(使用Json處理器)
  /// </summary>
  [pbr::OriginalName("UpdateA")] UpdateA = 10,
}

/// <summary>
/// 錯誤編號
/// </summary>
public enum ErrID {
  /// <summary>
  /// 成功
  /// </summary>
  [pbr::OriginalName("Success")] Success = 0,
  /// <summary>
  /// Json反序列化失敗
  /// </summary>
  [pbr::OriginalName("JsonUnmarshal")] JsonUnmarshal = 1,
  /// <summary>
  /// Proto反序列化失敗
  /// </summary>
  [pbr::OriginalName("ProtoUnmarshal")] ProtoUnmarshal = 2,
  /// <summary>
  /// ProtoRaven反序列化失敗
  /// </summary>
  [pbr::OriginalName("ProtoRavenUnmarshal")] ProtoRavenUnmarshal = 3,
  /// <summary>
  /// 資料庫執行失敗
  /// </summary>
  [pbr::OriginalName("SubmitFailed")] SubmitFailed = 4,
  /// <summary>
  /// Token不匹配
  /// </summary>
  [pbr::OriginalName("TokenNotMatch")] TokenNotMatch = 5,
}

#endregion


#endregion Designer generated code
