// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: raven.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from raven.proto</summary>
public static partial class RavenReflection {

  #region Descriptor
  /// <summary>File descriptor for raven.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static RavenReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CgtyYXZlbi5wcm90bxoZZ29vZ2xlL3Byb3RvYnVmL2FueS5wcm90byJoCgZS",
          "YXZlblMSEQoJbWVzc2FnZUlEGAEgASgFEiQKBmhlYWRlchgCIAEoCzIULmdv",
          "b2dsZS5wcm90b2J1Zi5BbnkSJQoHcmVxdWVzdBgDIAEoCzIULmdvb2dsZS5w",
          "cm90b2J1Zi5BbnkingEKBlJhdmVuQxIRCgltZXNzYWdlSUQYASABKAUSDQoF",
          "ZXJySUQYAiABKAUSJAoGaGVhZGVyGAMgASgLMhQuZ29vZ2xlLnByb3RvYnVm",
          "LkFueRIlCgdyZXF1ZXN0GAQgASgLMhQuZ29vZ2xlLnByb3RvYnVmLkFueRIl",
          "CgdyZXNwb25kGAUgAygLMhQuZ29vZ2xlLnByb3RvYnVmLkFueSIZCglSYXZl",
          "blRlc3QSDAoERGF0YRgBIAEoCUIMWgovbXNnczttc2dzYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.AnyReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::RavenS), global::RavenS.Parser, new[]{ "MessageID", "Header", "Request" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::RavenC), global::RavenC.Parser, new[]{ "MessageID", "ErrID", "Header", "Request", "Respond" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::RavenTest), global::RavenTest.Parser, new[]{ "Data" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
/// <summary>
/// Raven訊息資料, 客戶端傳送給伺服器
/// </summary>
public sealed partial class RavenS : pb::IMessage<RavenS>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<RavenS> _parser = new pb::MessageParser<RavenS>(() => new RavenS());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<RavenS> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::RavenReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RavenS() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RavenS(RavenS other) : this() {
    messageID_ = other.messageID_;
    header_ = other.header_ != null ? other.header_.Clone() : null;
    request_ = other.request_ != null ? other.request_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RavenS Clone() {
    return new RavenS(this);
  }

  /// <summary>Field number for the "messageID" field.</summary>
  public const int MessageIDFieldNumber = 1;
  private int messageID_;
  /// <summary>
  /// 訊息編號, 設置為int32以跟proto的列舉類型統一
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int MessageID {
    get { return messageID_; }
    set {
      messageID_ = value;
    }
  }

  /// <summary>Field number for the "header" field.</summary>
  public const int HeaderFieldNumber = 2;
  private global::Google.Protobuf.WellKnownTypes.Any header_;
  /// <summary>
  /// 標頭資料
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Google.Protobuf.WellKnownTypes.Any Header {
    get { return header_; }
    set {
      header_ = value;
    }
  }

  /// <summary>Field number for the "request" field.</summary>
  public const int RequestFieldNumber = 3;
  private global::Google.Protobuf.WellKnownTypes.Any request_;
  /// <summary>
  /// 要求資料
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Google.Protobuf.WellKnownTypes.Any Request {
    get { return request_; }
    set {
      request_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as RavenS);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(RavenS other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (MessageID != other.MessageID) return false;
    if (!object.Equals(Header, other.Header)) return false;
    if (!object.Equals(Request, other.Request)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (MessageID != 0) hash ^= MessageID.GetHashCode();
    if (header_ != null) hash ^= Header.GetHashCode();
    if (request_ != null) hash ^= Request.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (MessageID != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(MessageID);
    }
    if (header_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(Header);
    }
    if (request_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(Request);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (MessageID != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(MessageID);
    }
    if (header_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(Header);
    }
    if (request_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(Request);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (MessageID != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(MessageID);
    }
    if (header_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Header);
    }
    if (request_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Request);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(RavenS other) {
    if (other == null) {
      return;
    }
    if (other.MessageID != 0) {
      MessageID = other.MessageID;
    }
    if (other.header_ != null) {
      if (header_ == null) {
        Header = new global::Google.Protobuf.WellKnownTypes.Any();
      }
      Header.MergeFrom(other.Header);
    }
    if (other.request_ != null) {
      if (request_ == null) {
        Request = new global::Google.Protobuf.WellKnownTypes.Any();
      }
      Request.MergeFrom(other.Request);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          MessageID = input.ReadInt32();
          break;
        }
        case 18: {
          if (header_ == null) {
            Header = new global::Google.Protobuf.WellKnownTypes.Any();
          }
          input.ReadMessage(Header);
          break;
        }
        case 26: {
          if (request_ == null) {
            Request = new global::Google.Protobuf.WellKnownTypes.Any();
          }
          input.ReadMessage(Request);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          MessageID = input.ReadInt32();
          break;
        }
        case 18: {
          if (header_ == null) {
            Header = new global::Google.Protobuf.WellKnownTypes.Any();
          }
          input.ReadMessage(Header);
          break;
        }
        case 26: {
          if (request_ == null) {
            Request = new global::Google.Protobuf.WellKnownTypes.Any();
          }
          input.ReadMessage(Request);
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
/// Raven訊息資料, 伺服器傳送給客戶端
/// </summary>
public sealed partial class RavenC : pb::IMessage<RavenC>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<RavenC> _parser = new pb::MessageParser<RavenC>(() => new RavenC());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<RavenC> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::RavenReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RavenC() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RavenC(RavenC other) : this() {
    messageID_ = other.messageID_;
    errID_ = other.errID_;
    header_ = other.header_ != null ? other.header_.Clone() : null;
    request_ = other.request_ != null ? other.request_.Clone() : null;
    respond_ = other.respond_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RavenC Clone() {
    return new RavenC(this);
  }

  /// <summary>Field number for the "messageID" field.</summary>
  public const int MessageIDFieldNumber = 1;
  private int messageID_;
  /// <summary>
  /// 訊息編號, 設置為int32以跟proto的列舉類型統一
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int MessageID {
    get { return messageID_; }
    set {
      messageID_ = value;
    }
  }

  /// <summary>Field number for the "errID" field.</summary>
  public const int ErrIDFieldNumber = 2;
  private int errID_;
  /// <summary>
  /// 錯誤編號, 設置為int32以跟proto的列舉類型統一
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int ErrID {
    get { return errID_; }
    set {
      errID_ = value;
    }
  }

  /// <summary>Field number for the "header" field.</summary>
  public const int HeaderFieldNumber = 3;
  private global::Google.Protobuf.WellKnownTypes.Any header_;
  /// <summary>
  /// 標頭資料
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Google.Protobuf.WellKnownTypes.Any Header {
    get { return header_; }
    set {
      header_ = value;
    }
  }

  /// <summary>Field number for the "request" field.</summary>
  public const int RequestFieldNumber = 4;
  private global::Google.Protobuf.WellKnownTypes.Any request_;
  /// <summary>
  /// 要求資料
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Google.Protobuf.WellKnownTypes.Any Request {
    get { return request_; }
    set {
      request_ = value;
    }
  }

  /// <summary>Field number for the "respond" field.</summary>
  public const int RespondFieldNumber = 5;
  private static readonly pb::FieldCodec<global::Google.Protobuf.WellKnownTypes.Any> _repeated_respond_codec
      = pb::FieldCodec.ForMessage(42, global::Google.Protobuf.WellKnownTypes.Any.Parser);
  private readonly pbc::RepeatedField<global::Google.Protobuf.WellKnownTypes.Any> respond_ = new pbc::RepeatedField<global::Google.Protobuf.WellKnownTypes.Any>();
  /// <summary>
  /// 回應列表
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::Google.Protobuf.WellKnownTypes.Any> Respond {
    get { return respond_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as RavenC);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(RavenC other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (MessageID != other.MessageID) return false;
    if (ErrID != other.ErrID) return false;
    if (!object.Equals(Header, other.Header)) return false;
    if (!object.Equals(Request, other.Request)) return false;
    if(!respond_.Equals(other.respond_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (MessageID != 0) hash ^= MessageID.GetHashCode();
    if (ErrID != 0) hash ^= ErrID.GetHashCode();
    if (header_ != null) hash ^= Header.GetHashCode();
    if (request_ != null) hash ^= Request.GetHashCode();
    hash ^= respond_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (MessageID != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(MessageID);
    }
    if (ErrID != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(ErrID);
    }
    if (header_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(Header);
    }
    if (request_ != null) {
      output.WriteRawTag(34);
      output.WriteMessage(Request);
    }
    respond_.WriteTo(output, _repeated_respond_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (MessageID != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(MessageID);
    }
    if (ErrID != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(ErrID);
    }
    if (header_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(Header);
    }
    if (request_ != null) {
      output.WriteRawTag(34);
      output.WriteMessage(Request);
    }
    respond_.WriteTo(ref output, _repeated_respond_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (MessageID != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(MessageID);
    }
    if (ErrID != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ErrID);
    }
    if (header_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Header);
    }
    if (request_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Request);
    }
    size += respond_.CalculateSize(_repeated_respond_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(RavenC other) {
    if (other == null) {
      return;
    }
    if (other.MessageID != 0) {
      MessageID = other.MessageID;
    }
    if (other.ErrID != 0) {
      ErrID = other.ErrID;
    }
    if (other.header_ != null) {
      if (header_ == null) {
        Header = new global::Google.Protobuf.WellKnownTypes.Any();
      }
      Header.MergeFrom(other.Header);
    }
    if (other.request_ != null) {
      if (request_ == null) {
        Request = new global::Google.Protobuf.WellKnownTypes.Any();
      }
      Request.MergeFrom(other.Request);
    }
    respond_.Add(other.respond_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          MessageID = input.ReadInt32();
          break;
        }
        case 16: {
          ErrID = input.ReadInt32();
          break;
        }
        case 26: {
          if (header_ == null) {
            Header = new global::Google.Protobuf.WellKnownTypes.Any();
          }
          input.ReadMessage(Header);
          break;
        }
        case 34: {
          if (request_ == null) {
            Request = new global::Google.Protobuf.WellKnownTypes.Any();
          }
          input.ReadMessage(Request);
          break;
        }
        case 42: {
          respond_.AddEntriesFrom(input, _repeated_respond_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          MessageID = input.ReadInt32();
          break;
        }
        case 16: {
          ErrID = input.ReadInt32();
          break;
        }
        case 26: {
          if (header_ == null) {
            Header = new global::Google.Protobuf.WellKnownTypes.Any();
          }
          input.ReadMessage(Header);
          break;
        }
        case 34: {
          if (request_ == null) {
            Request = new global::Google.Protobuf.WellKnownTypes.Any();
          }
          input.ReadMessage(Request);
          break;
        }
        case 42: {
          respond_.AddEntriesFrom(ref input, _repeated_respond_codec);
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
/// Raven訊息測試資料
/// </summary>
public sealed partial class RavenTest : pb::IMessage<RavenTest>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<RavenTest> _parser = new pb::MessageParser<RavenTest>(() => new RavenTest());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<RavenTest> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::RavenReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RavenTest() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RavenTest(RavenTest other) : this() {
    data_ = other.data_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RavenTest Clone() {
    return new RavenTest(this);
  }

  /// <summary>Field number for the "Data" field.</summary>
  public const int DataFieldNumber = 1;
  private string data_ = "";
  /// <summary>
  /// 測試字串
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Data {
    get { return data_; }
    set {
      data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as RavenTest);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(RavenTest other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Data != other.Data) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Data.Length != 0) hash ^= Data.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Data.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Data);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Data.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Data);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Data.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Data);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(RavenTest other) {
    if (other == null) {
      return;
    }
    if (other.Data.Length != 0) {
      Data = other.Data;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Data = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Data = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
