// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: msgid.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from msgid.proto</summary>
public static partial class MsgidReflection {

  #region Descriptor
  /// <summary>File descriptor for msgid.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static MsgidReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cgttc2dpZC5wcm90byqMAQoFTXNnSUQSCwoHVW5rbm93bhAAEgkKBUpzb25R",
          "EAESCQoFSnNvbkEQAhIKCgZQcm90b1EQAxIKCgZQcm90b0EQBBIKCgZQTGlz",
          "dFEQBRIKCgZQTGlzdEEQBhIKCgZMb2dpblEQBxIKCgZMb2dpbkEQCBILCgdV",
          "cGRhdGVREAkSCwoHVXBkYXRlQRAKKrsBCgVFcnJJRBILCgdTdWNjZXNzEAAS",
          "EQoNSnNvblVubWFyc2hhbBABEhIKDlByb3RvVW5tYXJzaGFsEAISEgoOUExp",
          "c3RVbm1hcnNoYWwQAxIQCgxQTGlzdENvbnRleHQQBBIPCgtEYXRhYmFzZU5p",
          "bBAFEg0KCVN1Ym1pdE5pbBAGEhAKDFN1Ym1pdEZhaWxlZBAHEhMKD0FjY291",
          "bnROb3RFeGlzdBAIEhEKDVRva2VuTm90TWF0Y2gQCUIMWgovbXNnczttc2dz",
          "YgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::MsgID), typeof(global::ErrID), }, null, null));
  }
  #endregion

}
#region Enums
/// <summary>
/// 訊息編號
/// </summary>
public enum MsgID {
  /// <summary>
  /// 不明/錯誤訊息編號, 此編號不可使用
  /// </summary>
  [pbr::OriginalName("Unknown")] Unknown = 0,
  /// <summary>
  /// 要求Json
  /// </summary>
  [pbr::OriginalName("JsonQ")] JsonQ = 1,
  /// <summary>
  /// 回應Json
  /// </summary>
  [pbr::OriginalName("JsonA")] JsonA = 2,
  /// <summary>
  /// 要求Proto
  /// </summary>
  [pbr::OriginalName("ProtoQ")] ProtoQ = 3,
  /// <summary>
  /// 回應Proto
  /// </summary>
  [pbr::OriginalName("ProtoA")] ProtoA = 4,
  /// <summary>
  /// 要求PList
  /// </summary>
  [pbr::OriginalName("PListQ")] PlistQ = 5,
  /// <summary>
  /// 回應PList
  /// </summary>
  [pbr::OriginalName("PListA")] PlistA = 6,
  /// <summary>
  /// 要求登入(使用Json處理器)
  /// </summary>
  [pbr::OriginalName("LoginQ")] LoginQ = 7,
  /// <summary>
  /// 回應登入(使用Json處理器)
  /// </summary>
  [pbr::OriginalName("LoginA")] LoginA = 8,
  /// <summary>
  /// 要求更新(使用Json處理器)
  /// </summary>
  [pbr::OriginalName("UpdateQ")] UpdateQ = 9,
  /// <summary>
  /// 回應更新(使用Json處理器)
  /// </summary>
  [pbr::OriginalName("UpdateA")] UpdateA = 10,
}

/// <summary>
/// 錯誤編號
/// </summary>
public enum ErrID {
  /// <summary>
  /// 成功
  /// </summary>
  [pbr::OriginalName("Success")] Success = 0,
  /// <summary>
  /// json反序列化失敗
  /// </summary>
  [pbr::OriginalName("JsonUnmarshal")] JsonUnmarshal = 1,
  /// <summary>
  /// proto反序列化失敗
  /// </summary>
  [pbr::OriginalName("ProtoUnmarshal")] ProtoUnmarshal = 2,
  /// <summary>
  /// plist反序列化失敗
  /// </summary>
  [pbr::OriginalName("PListUnmarshal")] PlistUnmarshal = 3,
  /// <summary>
  /// plist上下文失敗
  /// </summary>
  [pbr::OriginalName("PListContext")] PlistContext = 4,
  /// <summary>
  /// 資料庫為空
  /// </summary>
  [pbr::OriginalName("DatabaseNil")] DatabaseNil = 5,
  /// <summary>
  /// 資料庫執行器為空
  /// </summary>
  [pbr::OriginalName("SubmitNil")] SubmitNil = 6,
  /// <summary>
  /// 資料庫執行失敗
  /// </summary>
  [pbr::OriginalName("SubmitFailed")] SubmitFailed = 7,
  /// <summary>
  /// 帳號不存在
  /// </summary>
  [pbr::OriginalName("AccountNotExist")] AccountNotExist = 8,
  /// <summary>
  /// token不匹配
  /// </summary>
  [pbr::OriginalName("TokenNotMatch")] TokenNotMatch = 9,
}

#endregion


#endregion Designer generated code
