name: lint

on:
  push:
    branches: [main]
    paths-ignore:
      - ".github/**"
      - ".idea/**"
      - "script/**"
  pull_request:
    branches: [main]
    paths-ignore:
      - ".github/**"
      - ".idea/**"
      - "script/**"

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: setup go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.11
