name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        redis: [7]
        mongo: ["7.0"]
    name: test | redis ${{ matrix.redis }} | mongo ${{ matrix.mongo }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: setup go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: setup protoc
        uses: arduino/setup-protoc@v3
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: setup protoc-go
        run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - name: setup redis
        uses: supercharge/redis-github-action@1.8.1
        with:
          redis-version: ${{ matrix.redis }}
      - name: setup mongo
        uses: supercharge/mongodb-github-action@1.12.1
        with:
          mongodb-version: ${{ matrix.mongo }}
      - name: test
        run: |
          go test -coverprofile=coverage.txt -covermode=atomic $(go list ./... | grep -v "support")
      - name: upload coverage to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          fail_ci_if_error: true
